### ISSUE TITLE
running the program 

### ISSUE THREAD

**Issue by kamkam2020** [KF-R/stratepai#1]
Hi, could you specify how to run these 3 files at windows ? 

thanks

**Comment by KF-R** [comment]
I added some generic installation instructions to the readme.

But for Windows (I'm rusty, but this should get you there):

Ensure you have Python installed and all three files are in the same directory.  
Then, create a text file called `my_env.py`, also in the same directory.
Edit that file so its contents include your OpenAI API key as follows:
```
API_KEY='INSERT_YOUR_API_KEY_HERE'
```

Then you should be able to use Python to run `stratepai.py`, which is the main file.

You might also like to like to review and/or edit the code in `stratepai_openai.py`, which contains the model selection and prompt.
